CREATE TABLE cdr_records (
    id BIGSERIAL PRIMARY KEY,
    call_id VARCHAR(255) UNIQUE NOT NULL,
    caller_number VARCHAR(50),
    callee_number VARCHAR(50),
    direction VARCHAR(20) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    answer_time TIMESTAMP,
    end_time TIMESTAMP,
    duration BIGINT,
    talk_duration BIGINT,
    ring_duration BIGINT,
    status VARCHAR(20),
    hangup_cause VARCHAR(100),
    agent_id UUID,
    queue_id BIGINT,
    extension VARCHAR(50),
    trunk VARCHAR(100),
    recording_id UUID,
    source_ip VARCHAR(45),
    destination_ip VARCHAR(45),
    media_server VARCHAR(255),
    call_type VARCHAR(50),
    cost DECIMAL(10,4),
    tenant_id UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE cdr_summaries (
    id BIGSERIAL PRIMARY KEY,
    summary_date DATE NOT NULL,
    tenant_id UUID,
    total_calls INT DEFAULT 0,
    answered_calls INT DEFAULT 0,
    missed_calls INT DEFAULT 0,
    total_duration BIGINT DEFAULT 0,
    avg_duration BIGINT DEFAULT 0,
    max_duration BIGINT DEFAULT 0,
    min_duration BIGINT DEFAULT 0,
    total_cost DECIMAL(18,2) DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE,
    UNIQUE(summary_date, tenant_id)
);

CREATE TABLE cdr_import_logs (
    id BIGSERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT,
    total_records INT DEFAULT 0,
    imported_records INT DEFAULT 0,
    failed_records INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'PENDING',
    error_message TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE
);
