apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcall

resources:
- namespace.yaml
- secrets.yaml
- service-registry.yaml
- config-server.yaml
- api-gateway.yaml
- microservices.yaml
- infra/postgresql-statefulset.yaml
- infra/redis-deployment.yaml
- infra/zookeeper-deployment.yaml
- infra/kafka-deployment.yaml
- infra/elasticsearch-statefulset.yaml
- infra/minio-deployment.yaml
- infra/clickhouse-statefulset.yaml
