spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vcall_survey_dev
    username: vcall
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.vcall: DEBUG
